### exp1

FROM alpine
LABEL author="anil"
CMD [ "sleep", "1d" ]

### exp2 

    FROM alpine
    LABEL author="anil"
    ADD 1.txt /
    CMD ["sleep", "1d"]

## exp3

FROM alpine 
LABEL author ="anil"
RUN echo "one" > 1.txt
RUN echo "two" > 2.txt
RUN echo "three" > 3.txt
CMD ["sleep", "1d"]

## exp4 

FROM alpine
LABEL author="anil"
RUN echo "one" > 1.txt && \
    echo "two" > 2.txt && \
    echo "three" > 3.txt
CMD ["sleep", "1d"]

